version: '3.4'
networks:
  k6:
  grafana:
  host:
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: nestjs-template
      MYSQL_DATABASE: nestjs-template
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq-stream
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_ERLANG_COOKIE: 'RabbitMQ-My-Cookies'
      RABBITMQ_DEFAULT_USER: 'nestjs-template'
      RABBITMQ_DEFAULT_PASS: 'nestjs-template'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:15672']
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s
  influxdb:
    image: influxdb:1.8
    networks:
      - k6
      - grafana
    ports:
      - 8086:8086
    environment:
      - INFLUXDB_DB=k6
  grafana:
    image: grafana/grafana:latest
    networks:
      - grafana
    ports:
      - 3000:3000
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ./tmp/dashboards:/var/lib/grafana/dashboards
      - "./scripts/k6-load-test-dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml"
      - "./scripts/k6-load-test-datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml"
  k6:
    image: grafana/k6:latest
    networks:
      - k6
      - host
    ports:
      - 6565:6565
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    volumes:
      - ./dist/scripts:/scripts
